version: '3.8'

services:
  backend:
    build:
        context: backend
        dockerfile: docker/Dockerfile
    container_name: copybase-backend
    restart: unless-stopped
    command: npm run start:dev

    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    networks:
      - mynet

  frontend:
    build:
        context: frontend
        dockerfile: docker/Dockerfile
    container_name: copybase-frontend
    restart: unless-stopped
    ports:
      - "3001:5173"
    volumes:
      - ./frontend:/app
    networks:
      - mynet
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0

networks:
  mynet:
    driver: bridge